### ISSUE TITLE
SDKCF-2871

### ISSUE THREAD

**Issue by donnie-jp** [rakutentech/ios-inappmessaging#10]
Requirements
WHAT: Investigate the implementation of a similar feature than in Android to register/unregister Activity (or Fragment)

WHY:
To prevent timing issue where a campaign could be displayed on a non-related screen (Activity/Fragment).

Campaign set to be displayed on screen A
User reach screen A and directly reach screen B
Campaign didn't had time to be displayed on screen A but gets displayed on screen B

Problem: This campaign was a tutorial for screen A

Output from the Investigation
* Confirmation if this improvement can be done
* Decide on implementation
* Sync with Android to align SDKs logic
* Draft spec (if needed)
* Create related implementation

**Comment by donnie-jp** [comment]
Explanation shared by Vincent:

> Here is the summary of my understanding regarding the IAM issue:
> 
> They are triggering the event in Home Tab - they expect to display the campaign here
> But in some instances, there is a quick transition to another tab
> So 1 out of 5 (I guess), the campaign is displayed in the other tab
> Based on our specs/behavior, this is an expected behavior
> It is just the timing of the campaign/event processing
> 
> In Android, this can be handled by register and unregister API
> 
> An activity can be registered if it will allow IAM to be displayed, then it should be unregister when transitioning to another activity
> 
> They are using fragments for the tab which will require investigation to handle.
> In iOS, I’m not sure if there is a way to this with the same logic in Android

**Comment by imaginaris** [comment]
Proposed solution:

1. Extend SDK's API method `logEvent` by adding a parameter `context` of new type `EventContext`
2. Add new optional delegate with method `inAppMessagingShouldShowCampaignMessage` that will accept campaign's title and contexts from logged events as a parameter and expect a bool value in return

Example:
A host app logs an event with context named "tutorial". When a campaign triggered by that event is about to be displayed it will call the new delegate method with "tutorial" context to confirm or abort displaying the message.

**Comment by donnie-jp** [comment]
Closed in https://github.com/rakutentech/ios-inappmessaging/pull/13
